const FUNCTION_RESPONSE = {
  USER_ALREADY_REGISTERED: "USER_ALREADY_REGISTERED",
  INVALID_NAME: "INVALID_NAME",
  INVALID_DOB: "INVALID_DOB",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
};

const USER_DATA_FILE_NAME = "../data/user-data.json";

module.exports = {
  FUNCTION_RESPONSE,
  USER_DATA_FILE_NAME,
};
